/* Occupancy grid + A*. Diagonal moves cannot cut the corner of a wall or counter. */
'use strict';
window.FestaNavigation=class {
 constructor(world){this.world=world;this.step=.70;this.x0=-67;this.z0=-58;this.nx=184;this.nz=244;this.size=this.nx*this.nz;this.open=new Uint8Array(this.size);for(let z=0;z<this.nz;z++)for(let x=0;x<this.nx;x++){let p=this.point(z*this.nx+x);this.open[z*this.nx+x]=world.isWalkable(p[0],p[1],.34)?1:0;}}
 point(i){return[this.x0+(i%this.nx)*this.step,this.z0+Math.floor(i/this.nx)*this.step];}
 index(p){return Math.round((p[1]-this.z0)/this.step)*this.nx+Math.round((p[0]-this.x0)/this.step);}
 nearest(p){let x=Math.round((p[0]-this.x0)/this.step),z=Math.round((p[1]-this.z0)/this.step),best=-1,dist=Infinity;for(let r=0;r<18;r++){for(let dz=-r;dz<=r;dz++)for(let dx=-r;dx<=r;dx++){if(r&&Math.abs(dx)!==r&&Math.abs(dz)!==r)continue;let xx=x+dx,zz=z+dz;if(xx<0||xx>=this.nx||zz<0||zz>=this.nz)continue;let i=zz*this.nx+xx;if(!this.open[i])continue;let q=this.point(i),d=Math.hypot(q[0]-p[0],q[1]-p[1]);if(d<dist){dist=d;best=i;}}if(best>=0)return best;}return-1;}
 lineFree(a,b,r=.30){let d=Math.hypot(b[0]-a[0],b[1]-a[1]),n=Math.ceil(d/.16);for(let i=0;i<=n;i++)if(!this.world.isWalkable(a[0]+(b[0]-a[0])*i/Math.max(1,n),a[1]+(b[1]-a[1])*i/Math.max(1,n),r))return false;return true;}
 find(start,end){const src=this.nearest(start),dst=this.nearest(end);if(src<0||dst<0)return null;let costs=new Float32Array(this.size);costs.fill(Infinity);let parents=new Int32Array(this.size);parents.fill(-1);let visited=new Uint8Array(this.size),heap=[];const push=(i,f)=>{let v={i,f},k=heap.length;heap.push(v);while(k){let p=(k-1)>>1;if(heap[p].f<=v.f)break;heap[k]=heap[p];k=p;}heap[k]=v;};const pop=()=>{let top=heap[0],v=heap.pop();if(heap.length){let k=0;while(2*k+1<heap.length){let c=2*k+1;if(c+1<heap.length&&heap[c+1].f<heap[c].f)c++;if(heap[c].f>=v.f)break;heap[k]=heap[c];k=c;}heap[k]=v;}return top.i;};let tx=dst%this.nx,tz=Math.floor(dst/this.nx),heur=i=>{let dx=Math.abs(i%this.nx-tx),dz=Math.abs(Math.floor(i/this.nx)-tz);return Math.max(dx,dz)+.41421356*Math.min(dx,dz);};costs[src]=0;push(src,heur(src));let found=false;
  while(heap.length){let i=pop();if(visited[i])continue;visited[i]=1;if(i===dst){found=true;break;}let x=i%this.nx,z=Math.floor(i/this.nx);for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dz)continue;let xx=x+dx,zz=z+dz;if(xx<0||xx>=this.nx||zz<0||zz>=this.nz)continue;let j=zz*this.nx+xx;if(!this.open[j]||visited[j]||(dx&&dz&&(!this.open[z*this.nx+xx]||!this.open[zz*this.nx+x])))continue;let cost=costs[i]+(dx&&dz?1.41421356:1);if(cost<costs[j]){costs[j]=cost;parents[j]=i;push(j,cost+heur(j));}}}
  if(!found)return null;let route=[],i=dst;while(i>=0){route.push(this.point(i));if(i===src)break;i=parents[i];}route.reverse();if(this.lineFree(start,route[0]))route.unshift([...start]);if(this.lineFree(route[route.length-1],end))route.push([...end]);let smooth=[route[0]],k=0;while(k<route.length-1){let j=route.length-1;while(j>k+1&&!this.lineFree(route[k],route[j]))j--;smooth.push(route[j]);k=j;}return smooth;
 }
};
